name: change 
on:
  workflow_run:
    workflows: ["Clash-for-Windows Update Check"]
    types:
      - completed
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11,需要repo和workflow权限
      - name: change variables
        run: |
          
          sed -i -E "s/(version: ")[0-9]+( [^[:space:]]+ \* \* \*")/\1$(($env.version))\2/g" .github/workflows/main.yml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "change var"
          git push origin master
