name: 'GitHub Actions Send'


on:
  workflow_run:
    workflows: ["刷步数"]
    types:
      - completed
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v1

      - name: 'Install node'
        uses: actions/setup-node@v1

      - name: 'Install NPM dependencies'
        run: npm install

      - name: 'Run node'
        run: node index.js

        env:
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          
